### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by crutchcorn** [crutchcorn/unfurl#1]
- [ ] Delete remainder empty paths (preferably by scanning the top directory and removing all empty folders)
- [ ] Add a way to see the folder tree and which directories contain files
- [ ] `Walk` through directories to handle many different folders to unfurl
  - [ ] Make respect preserve last folder option
- [x] Utilize command line arguments
- [x] Load script path from "`argv`"
- [x] Make all files from folder move into top directory (rather than being hidden in another folder)
- [x] Allow unfurl to occur with only one directory - not just many
  > `for folder in listdir(scriptpath):` is to blame for this.
- [x] Possibly rework unfurl process by using `walk`'d filenames and folderpath (see below)
